6. Welcome

diff --git a/0x00-shell_basics/6-firstdirectory b/0x00-shell_basics/6-firstdirectory
--- a/0x00-shell_basics/6-firstdirectory
+++ b/0x00-shell_basics/6-firstdirectory
@@ -1,2 +1,17 @@
 #!/bin/bash
-directory_path="/tmp/my_first_directory"
+directory_path="/tmp/my_first_directory
+
+if [ -d "$directory_path" ]; then
+    echo "Directory '$directory_path' already exists."
+else
+    # Create the directory
+    mkdir "$directory_path"
+    
+    # Check if the directory creation was successful
+    if [ $? -eq 0 ]; then
+        echo "Directory '$directory_path' created successfully."
+    else
+        echo "Failed to create directory '$directory_path'."
+    fi
+fi
+"
